### ISSUE TITLE
Spammy bug with AntiAura

### ISSUE THREAD

**Issue by PsychoLynx** [TechzoneMC/NPCLib#10]
Hey! I'm using the newest versions of both AntiAura and NPCLib, this happens every time a player first starts moving on the server :/ (Running the latest 1.8.6 Spigot)

[22:57:32] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to AntiAura v5.05
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:269) [spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_67]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_67]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]
Caused by: java.lang.NoClassDefFoundError: de/inventivegames/npc/NPCLib
	at a.j.f(PacketStuff.java:39) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_67]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	... 15 more
Caused by: java.lang.ClassNotFoundException: de.inventivegames.npc.NPCLib
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_67]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_67]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_67]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_67]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
	at a.j.f(PacketStuff.java:39) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_67]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.6-latest.jar:git-Spigot-6a6b839-b0e81a4]
	... 15 more

**Comment by Techcable** [comment]
Use inventivetalent's NPCLib.
